-- Disable check constraints temporarily if needed, though usually not necessary for initial schema
-- SET session_replication_role = 'replica'; 

-- ===================================
-- 1. Create Tables
-- ===================================

-- PostgreSQL equivalent of MySQL ENUM: uses a custom TYPE
CREATE TYPE user_role AS ENUM ('CAR_OWNER', 'GARAGE_ADMIN', 'SYSTEM_ADMIN', 'MECHANIC');

CREATE TABLE users (
    -- Equivalent of BIGINT AUTO_INCREMENT PRIMARY KEY:
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    -- Equivalent of BOOLEAN DEFAULT TRUE:
    enabled BOOLEAN DEFAULT TRUE, 
    -- Use the custom TYPE for the role
    role user_role NOT NULL
);

-- Note: The rest of these tables are likely only shells, as JPA would manage the columns. 
-- However, we must ensure the primary key syntax is correct.

CREATE TABLE car_owners (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

CREATE TABLE garages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

CREATE TABLE mechanics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

CREATE TABLE services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description TEXT,
    -- DECIMAL(10,2) is standard and works fine
    price DECIMAL(10,2) NOT NULL 
);

CREATE TABLE bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    garage_id BIGINT NOT NULL,
    service_id BIGINT NOT NULL,
    mechanic_id BIGINT,
    -- Equivalent of DATETIME DEFAULT CURRENT_TIMESTAMP:
    booking_date TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, 
    status VARCHAR(50) DEFAULT 'PENDING'
);

-- ===================================
-- 2. Create Foreign Key Constraints
-- ===================================

-- Since you are relying on JPA, it's best to explicitly define the FKs here 
-- if they are not defined via annotations (or if you want Flyway to own them).

ALTER TABLE bookings
    ADD CONSTRAINT fk_booking_user
    FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE bookings
    ADD CONSTRAINT fk_booking_garage
    FOREIGN KEY (garage_id) REFERENCES garages (id);

ALTER TABLE bookings
    ADD CONSTRAINT fk_booking_service
    FOREIGN KEY (service_id) REFERENCES services (id);
    
-- Mechanic ID can be NULL, so this constraint is optional.
ALTER TABLE bookings
    ADD CONSTRAINT fk_booking_mechanic
    FOREIGN KEY (mechanic_id) REFERENCES mechanics (id);