CREATE TABLE users (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    enabled BOOLEAN DEFAULT TRUE,
    role ENUM('CAR_OWNER', 'GARAGE_ADMIN', 'SYSTEM_ADMIN', 'MECHANIC') NOT NULL
);

CREATE TABLE carOwners (
    id BIGINT AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE garages (
    id BIGINT AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE mechanics (
    id BIGINT AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE services (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    description TEXT,
    price DECIMAL(10,2) NOT NULL
);

CREATE TABLE bookings (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    garage_id BIGINT NOT NULL,
    service_id BIGINT NOT NULL,
    mechanic_id BIGINT,
    booking_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(50) DEFAULT 'PENDING'
);
